# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{txter}
  s.version = "2.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jack Danger Canty"]
  s.date = %q{2010-03-17}
  s.description = %q{Drop-in functionality to let Ruby apps send and receive TXT messages}
  s.email = %q{gitcommit@6brand.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/4info_templates/confirm.haml",
     "lib/4info_templates/deliver.haml",
     "lib/4info_templates/unblock.haml",
     "lib/configuration.rb",
     "lib/contactable.rb",
     "lib/controller.rb",
     "lib/gateway.rb",
     "lib/gateway_4info.rb",
     "lib/gateway_twilio.rb",
     "lib/txter.rb",
     "test/.gitignore",
     "test/database.yml",
     "test/gateway_4info_test.rb",
     "test/gateway_twilio_test.rb",
     "test/test_helper.rb",
     "test/txter_contactable_test.rb",
     "test/txter_controller_test.rb",
     "test/txter_module_test.rb",
     "txter.gemspec"
  ]
  s.homepage = %q{http://github.com/JackDanger/txter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Send and receive SMS messages simply via the Twilio gateway or the 4info.com gateway}
  s.test_files = [
    "test/gateway_4info_test.rb",
     "test/gateway_twilio_test.rb",
     "test/test_helper.rb",
     "test/txter_contactable_test.rb",
     "test/txter_controller_test.rb",
     "test/txter_module_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

